global:
  scrape_interval: "10s"

scrape_configs:
  - job_name: 'auth-microservice'
    static_configs:
      - targets: ['host.docker.internal:3000']   #if auth service on local machin and prom is on docker